config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users
  root to: 'pages#home'
  resources :equipment_listings
  resources :services
  resources :conversations do
    resources :messages
  end
  resources :users, only: :index

  #Allows me to sort listings via category by using the Item_type ID in params
  resources :item_types, only: :index do
    resources :equipment_listings, only: :index
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
  validates_length_of :title, maximum: 60
  
  validates :location, presence: true
  
  validates :description, presence: true
  validates_length_of :description, maximum: 500

  validates :price, presence: true

  validates :photo, content_type: [:png, :jpg, :jpeg]

  has_one_attached :photo
  
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_service, only: [:show, :update, :edit, :destroy]
    before_action :check_auth, except: [:index, :show, :new, :create]

    def index 
        # Stores all service listings in descending order of time created. .page allows pagination through kaminari gem
        @services = Service.order(created_at: :desc).page(params[:page])
    end

    def show 
        # Session is stored in memory whenever a user views a listing. Session is used to allocate the recipient_Id when a user wants to send a message to the owner of the listing
        session[:listing_id] = @service.user_id
    end

    def new
        @service = Service.new
    end


    #@service.user stores the current user in memory to assign the user_id automatically when a listing is created
    def create
        @service = Service.new(service_params)
        @service.user = current_user
        if @service.save
            redirect_to @service
        else
            flash.now[:errors] = @service.errors.full_messages
            render action: 'new'
        end
    end

    def destroy
        @service.destroy
        redirect_to services_path
    end

    def edit

    end

    def update
        # Fills edit form with current params and provides error handling
        if @service.update(service_params)
            redirect_to @service
        else
            flash.now[:errors] = @service.errors.full_messages
            render action: 'edit'
        end
    end

    private
    # Checks the authorization of a user through Pundit
    def check_auth
        authorize @service
    end
    # Sanitizes input for permitted params
    def service_params 
        params.require(:service).permit(:id, :user_id, :title, :description, :price, :location, :photo)
    end

    # Sets the current service listing for each action assigned by before_action helper for user to view
    def set_service
        @service = Service.find(params[:id])
    end

end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<script>
  function initAutocomplete() {

    // Create the search box and link it to the UI element.
    const inputs = document.getElementsByClassName("google");
    for (let i = 0; i < inputs.length; i++) {
      const searchBox = new google.maps.places.SearchBox(inputs[i]);

      // Listen for the event fired when the user selects a prediction and retrieve
      // more details for that place.
      searchBox.addListener("places_changed", () => {
        const places = searchBox.getPlaces();

        if (places.length == 0) {
          return;
        }
      });
    }
  }
</script>
<%= simple_form_for @service do |f| %>

    <%= f.error_notification %>

    <p>
        <%= f.input :title %>
    </p>
    <p> 
        <%= f.input :description %> 
    </p>
    <p> 
        <%= f.input :location, label: "City/Suburb", :input_html => {class: 'google'} %> 
    </p>
    <p> 
        <%= f.input :price %> 
    </p>
    <p>
        <%= f.input :photo %>
    </p>
    <p>
        <%= f.submit %>
    </p>

<% end %>
<script
      src=<%="https://maps.googleapis.com/maps/api/js?key=#{ENV["GOOGLE_PLACES_API"]}&callback=initAutocomplete&libraries=places&v=weekly"%>
      async
    ></script>

app/views/services/edit.html.erb
<h1>Edit Service</h1>

<%= render 'form' %>

app/views/services/index.html.erb
<div class='container'>
    <div class='row p-1'>
        <div class='col'>
            <p> <%= link_to "Create Service Listing", new_service_path, class: "btn btn-primary"%> </p>
            <p><%= paginate @services %></p>
            <% @services.each do |service| %>
            <div class='card mb-3 border-dark'>
                <div class='row g-0 text-center'>
                    <div class='col-md-3 d-flex justify-content-center p-1'>
                        <div>
                            <% if !service.photo.attached? %>
                                <%= image_tag("http://via.placeholder.com/50", width: 175, height: 175, class: 'rounded d-flex image-fluid')%>
                            <% else %>
                                <%= cl_image_tag service.photo.key, crop: :scale, width: 175, height: 175, cloud_name: 'boggyboi', class: 'rounded image-fluid'%>
                            <% end %>
                        </div>
                    </div>
                    <div class='col-md-7 d-flex'>
                        <div class='card-body d-flex flex-column justify-content-evenly'>
                            <h4 class="card-title"> <%= link_to service.title, service_path(service)%> </h4>
                            <p class="card-text"><%= service.description %></p>
                        </div>
                    </div>
                    <div class='col-md-2 d-flex flex-column justify-content-evenly'>
                        <p><%= service.user.name %></p>
                        <p> $<%= service.price %> </p>
                        <p> <%= service.location %> </p>
                        <p>
                            <%= link_to "Edit", edit_service_path(service) if policy(service).edit? %>
                            <%= link_to "Delete", service, method: :delete, data: {confirm: "Are you sure" } if policy(service).destroy?  %>
                        </p>
                    </div>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form' %>

app/views/services/show.html.erb
<div class='container text-center'>
    <div class='row p-1 d-flex justify-content-center'>
        <div class='col-md-6 border d-flex flex-column justify-content-center align-items-center'>

        <% if !@service.photo.attached? %>
            <%= image_tag("http://via.placeholder.com/50", width: 150, height: 150)  %>
        <% else %>
                <div>
                    <%= cl_image_tag @service.photo.key, crop: :scale, width: 150, cloud_name: 'boggyboi' %>
                </div>
        <% end %>

            <div class='row'>
                <h2> <%= @service.title  %></h2>
                <p>Description: <%= @service.description %></p>
            </div>
            <div class='row'>
                <div class='col'>
                    <h2>Price: $<%= @service.price %> </h2>
                    <p>Owner: <%= @service.user.name %></p>
                    <p>Location: <%= @service.location %> </p>
                </div>
                    <div class='col d-flex flex-column justify-content-evenly'>
                        <% if user_signed_in? == false || current_user.id != @service.user_id  %>
                            <%= link_to "Message Owner", new_conversation_path, class: 'btn btn-primary my-2' %>
                            <% else %>
                        <% end %>
                        <p class='d-flex justify-content-evenly'>
                            <%= link_to "Back", services_path, class: 'btn btn-primary my-2' %>
                            <%= link_to "Edit", edit_service_path, class: 'btn btn-primary my-2' if policy(@service).edit? %>
                            <%= link_to "Delete", @service, class: 'btn btn-primary my-2', method: :delete, data: {confirm: "Are you sure?"} if policy(@service).destroy? %>
                        </p>
                    </div>
            </div>
    
        </div>
    </div>
</div>