config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users
  root to: 'pages#home'
  resources :equipment_listings
  resources :services
  resources :conversations do
    resources :messages
  end
  resources :users, only: :index

  #Allows me to sort listings via category by using the Item_type ID in params
  resources :item_types, only: :index do
    resources :equipment_listings, only: :index
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_conversation, only: [:update, :show, :destroy, :edit]

    def index 
        
        @conversations = current_user.mailbox.conversations.page(params[:page]).per(5)
        session[:listing_id] = nil
    end

    def show 
    end

    def new 
        # Prevents messages/conversations being shown twice
        @recipients = User.all - [current_user]
    end 

    def create 
        recipient = User.find(params[:user_id])

        # Provides validation when a user tries to send a message with empty fields
        if get_body[:body].empty? || get_subject[:subject].empty?
            flash[:alert] = "You cannot send an empty message"
            redirect_to new_conversation_path
        else
            receipt = current_user.send_message(recipient, get_body[:body], get_subject[:subject])
            redirect_to conversation_path(receipt.conversation)
        end
    end

    def destroy 
        @conversation.destroy
        redirect_to conversations_path
    end


    private
    # Sanitizes input for the body of a message
    def get_body
        params.permit(:body)
    end

    # Sanitizes input for the subject of a message
    def get_subject 
        params.permit(:subject)
    end
    # Sets the current conversation for each action assigned by before_action helper for user to view
    def set_conversation
        @conversation = current_user.mailbox.conversations.find(params[:id])
    end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/index.html.erb
<div class='card text-center'>
    <h1> All conversations</h1>
        <%= paginate @conversations %>
    <% if @conversations.empty? %>
        <h6> You have no conversations </h6>
    <% end %>
    <% @conversations.each do |conversation| %>
        <div>
            <%= link_to conversation.subject + " - " + conversation.recipients.delete_if {|x| x == current_user }[0].name, conversation_path(conversation) %>
            |
            <%= link_to "Delete", conversation_path(conversation), method: :delete, data: {confirm: "Are you sure" } %>
        </div>
    <% end %>
</div>

app/views/conversations/new.html.erb
<h1> New Conversation </h1>

<%= form_tag conversations_path, method: :post do  %>
    <%= hidden_field_tag :user_id, session[:listing_id] %>
    <div>
        <%= text_field_tag :subject, "Subject" %>
    </div>
    <div>
        <%= text_area_tag :body, "Leave a message!" %>
    </div>

    <%= submit_tag %>
<% end %>

app/views/conversations/show.html.erb
<div class='text-center'>
    <h1><%= @conversation.subject %></h1>
    <p>
        <%= link_to "Delete Conversation", conversation_path(@conversation), method: :delete, data: {confirm: "Are you sure" }   %>
    </p>
    
    <% @conversation.receipts_for(current_user).each do |receipt| %>
        <div>
            <div> <%= receipt.message.sender.name %> commented: </div>
            <p> <%= receipt.message.body %> </p>
        </div>
    <% end %>
    
    <%= form_tag conversation_messages_path(@conversation), method: :post do %>
        <div>
            <%= text_area_tag :body %>
        </div>
        <%= submit_tag "Send message" %>
    <% end %>
</div>