config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users
  root to: 'pages#home'
  resources :equipment_listings
  resources :services
  resources :conversations do
    resources :messages
  end
  resources :users, only: :index

  #Allows me to sort listings via category by using the Item_type ID in params
  resources :item_types, only: :index do
    resources :equipment_listings, only: :index
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  has_many :equipment_listings, dependent: :destroy
  has_many :services, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :phone, length: { maximum: 12 }

  acts_as_messageable

  before_destroy { messages.destroy_all }

  # Creates a default role when a user signs up
  after_create :default_role

  def default_role
    add_role(:member)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class='text-center'>
    <h1>Account Details</h1>
    
    <p>Name: <%= current_user.name %> </p>
    
    <p>Email: <%= current_user.email %> </p>
    
    <p>Phone: <%= current_user.phone %> </p>
    
    <p> <%= link_to "Edit Account Details", edit_user_registration_path %>  </p>
    <hr>

    <div class='d-flex flex-column justify-content-center align-items-center'>
        <h3>Current Equipment Listed</h3>
        <table>
            <tr>
                <th>Title</th>
                <th>Category</th>
                <th>Actions</th>
            </tr>
            <% current_user.equipment_listings.each do |listing| %>
                <tr>
                    <td> <%= link_to listing.title, equipment_listing_path(listing)%> </td>
                    <td><%= listing.item_type.name %></td>
                    <td>
                        <%= link_to "Edit", edit_equipment_listing_path(listing) if policy(listing).edit? %>
                    |
                        <%= link_to "Delete", listing, method: :delete, data: {confirm: "Are you sure" } if policy(listing).destroy? %>
                    </td>
                </tr>
            <% end %>
        </table>
    </div>
    <hr>
    <div class='d-flex flex-column justify-content-center align-items-center'>
        <h3>Current Service Listings</h3>
        <table>
            <tr>
                <th>Title</th>
                <th>Actions</th>
            </tr>
            <% current_user.services.each do |service| %>
                <tr>
                    <td> <%= link_to service.title, service_path(service)%> </td>
                    <td>
                        <%= link_to "Edit", edit_service_path(service) if policy(service).edit? %>
                    |
                        <%= link_to "Delete", service, method: :delete, data: {confirm: "Are you sure" } if policy(service).destroy?  %>
                    </td>
                </tr>
            <% end %>
        </table>
    </div>
</div>