config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users
  root to: 'pages#home'
  resources :equipment_listings
  resources :services
  resources :conversations do
    resources :messages
  end
  resources :users, only: :index

  #Allows me to sort listings via category by using the Item_type ID in params
  resources :item_types, only: :index do
    resources :equipment_listings, only: :index
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    has_one :equipment_listing, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/condition.rb
class Condition < ApplicationRecord
    has_many :equipment_listings, dependent: :destroy
end

app/models/equipment_listing.rb
class EquipmentListing < ApplicationRecord
  belongs_to :user
  belongs_to :item_type
  belongs_to :condition

  has_many_attached :photos
  
  validates :photos, limit: { min: 0, max: 5, message: 'Max file limit reached. 5 Files max' }, 
                     content_type: [:png, :jpg, :jpeg]

  validates :description, presence: true 
  validates_length_of :description, maximum: 500

  validates :title, presence: true
  validates_length_of :title, maximum: 60

  validates :address, presence: true

  validates :price, presence: true

end

app/models/item_type.rb
class ItemType < ApplicationRecord
    has_many :equipment_listings, dependent: :destroy
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
  validates_length_of :title, maximum: 60
  
  validates :location, presence: true
  
  validates :description, presence: true
  validates_length_of :description, maximum: 500

  validates :price, presence: true

  validates :photo, content_type: [:png, :jpg, :jpeg]

  has_one_attached :photo
  
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  has_many :equipment_listings, dependent: :destroy
  has_many :services, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :phone, length: { maximum: 12 }

  acts_as_messageable

  before_destroy { messages.destroy_all }

  # Creates a default role when a user signs up
  after_create :default_role

  def default_role
    add_role(:member)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     include Pundit
    protect_from_forgery with: :exception

     before_action :configure_permitted_parameters, if: :devise_controller?

     protected
          # Sanitizes input for permitted params
          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :phone, :email, :password)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :phone, :email, :password, :current_password)}
          end
    
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_conversation

    def create
        # Provides validation when a user tries to send a message with empty fields
        if message_params[:body].empty?
            flash[:alert] = "You cannot send an empty message"
            redirect_to conversation_path(@conversation)
        else
            receipt = current_user.reply_to_conversation(@conversation, message_params[:body])
            redirect_to conversation_path(receipt.conversation)
            p message_params
        end
    end


    private
    # Sanitizes input for the body of a message
    def message_params
        params.permit(:body)
    end

    # Sets the current conversation for each action assigned by before_action helper for user to view
    def set_conversation
        @conversation = current_user.mailbox.conversations.find(params[:conversation_id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # Allows home page to view the latest listings
  def home
    @equipment_listings = EquipmentListing.order(created_at: :desc)
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_service, only: [:show, :update, :edit, :destroy]
    before_action :check_auth, except: [:index, :show, :new, :create]

    def index 
        # Stores all service listings in descending order of time created. .page allows pagination through kaminari gem
        @services = Service.order(created_at: :desc).page(params[:page])
    end

    def show 
        # Session is stored in memory whenever a user views a listing. Session is used to allocate the recipient_Id when a user wants to send a message to the owner of the listing
        session[:listing_id] = @service.user_id
    end

    def new
        @service = Service.new
    end


    #@service.user stores the current user in memory to assign the user_id automatically when a listing is created
    def create
        @service = Service.new(service_params)
        @service.user = current_user
        if @service.save
            redirect_to @service
        else
            flash.now[:errors] = @service.errors.full_messages
            render action: 'new'
        end
    end

    def destroy
        @service.destroy
        redirect_to services_path
    end

    def edit

    end

    def update
        # Fills edit form with current params and provides error handling
        if @service.update(service_params)
            redirect_to @service
        else
            flash.now[:errors] = @service.errors.full_messages
            render action: 'edit'
        end
    end

    private
    # Checks the authorization of a user through Pundit
    def check_auth
        authorize @service
    end
    # Sanitizes input for permitted params
    def service_params 
        params.require(:service).permit(:id, :user_id, :title, :description, :price, :location, :photo)
    end

    # Sets the current service listing for each action assigned by before_action helper for user to view
    def set_service
        @service = Service.find(params[:id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/equipment_listings_helper.rb
module EquipmentListingsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Src</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous" defer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous" defer></script>
    <link
      rel="stylesheet"
      href="https://unpkg.com/swiper/swiper-bundle.min.css"
    />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container-fluid">
            <div class="navbar-brand mb-0 h1">
              <%= link_to image_tag("logo2.png", height: 75), root_path, class: "navbar-brand mb-0 h1"%>
              The Pro Shop
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
              <ul class="navbar-nav me-auto">
                <li class="nav-item">
                  <%= link_to "Home", root_path, class: "nav-link active" %>
                    <span class="visually-hidden">(current)</span>
                  </a>
                </li>
                <li class="nav-item">
                  <%= link_to "Equipment", equipment_listings_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Services", services_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Messages", conversations_path, class: "nav-link" %>
                </li>
                    <% if user_signed_in? %>
                      <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">My Account</a>
                      <div class="dropdown-menu">
                        <%= link_to current_user.name, users_index_path, class: "dropdown-item" %>
                      <div class="dropdown-divider"></div>
                        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                    <% else %>
                      <%= link_to "login/signup", new_user_session_path, class: "nav-link" %>
                    <% end %>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </nav>

    </header>
    <% if notice %>
      <p class="notice bg-info bg-gradient text-center"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert bg-danger text-center"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<main>

    <section class='py-5 text-center container'>
        <div class='row py-lg-5'>
            <div class='col-lg-6 col-md-8 mx-auto'>
                <h1 class='fw-light'>Welcome To The Pro Shop</h1>
                <p class='lead text-muted'>
                    List your second hand golfing equipment or services here
                </p>
                <p>
                    <%= link_to 'Shop Equipment Now'.html_safe, equipment_listings_path, class: 'btn btn-primary my-2' %>
                    <%= link_to 'View Golfing Services'.html_safe, services_path, class: 'btn btn-primary my-2' %>
                </p>
                <p>
                    <%= link_to 'Post an ad!'.html_safe, new_equipment_listing_path, class: 'btn btn-secondary my-2' %>
                </p>
            </div>
        </div>
        <h4 class='text-center'>Latest Listings</h4>
    </section>
    <div class='album py-5'>
        <div class='container'>
            <div class='row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-4  g-3'>
                <% @equipment_listings[0..3].each do |listing| %>
                <div class='col'>
                    <div class='card shadow-sm text-center'>
                        <% if !listing.photos.attached? %>
                            <%= image_tag("http://via.placeholder.com/50", width: '100%', height: "100%")  %>
                        <% else %>
                            <%= cl_image_tag listing.photos.first.key, crop: :fill, cloud_name: 'boggyboi', class: 'rounded img-fluid d-flex justify-content-center'%>
                        <% end %>
                        <h4> <%= link_to listing.title, equipment_listing_path(listing) %> </h4>
                        <h6>Price: $<%= listing.price %> </h6>
                        <p>Location: <%= listing.address %> </p>
                    </div>
                </div>
                <% end %>
            </div>
        </div>    
    </div>
</main>